jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:4.8.2 # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run:
          name: test
          command: npm test